language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- "./generate_secrets.sh"
- platformio run
- gpg --keyserver pgp.mit.edu --recv-keys 1C0FF61B
- gpg --trust-model always --output firmware.bin.gpg --recipient 8D451F061C0FF61B --encrypt .pioenvs/esp01/firmware.bin
env:
  global:
    secure: RRO6VkI3+w4mgLjQGdC7wTagNAcEaRr9G095u5aFKp6OJeNIr3wL9bD2E/WiJ25/tldktl+4G41WPhRTbVWiuIAZlagY/7iHXlmCxTNFJC7wYGudNWWiCAsVU2ERoO98lRTn9Z4+KMlx0s1KalSP7a6PWjKfv7gjR8plaL86VEjJ6ZoJ75YQ4al8CBiDnTDNUKZXQfHPZs6Rl4DSSZ4DvZXsweqlN4g15+SbR9vsiPslQ6sIFdV/jmTZwwiv7YuoqZzd3+kdugkP+zxwL6t15rHnuC7T8NYX0mUSSopAhyiCAhwc/DHcPaOvKqeJtp9z5wLa4UNC7SfjnkY5NAITRMv70kmHMOC/TDxs9KhLzIfqUuDe5DZGi7aUjPebgMBhTchczZCI7Dn1gkYfyVRQdyToa2xvI4X1kU+WuUX9D79Hr08n/lKIIo34+ZSU0UsEg2K8SkkCRGpWZOs2G/I/rozkS3ykNxuNvsuTFAMNisR6yOsF52DATEHOx2MORHxct4Lg1DvkIIpqxFpIqIj8vvXO7fV74JVHkKCAoIFWvMUqx29w6qDawjPRkQNQgbszUwAflAOTW/0ejPth0YKGXFO5Pl9MJoUzofAdkBvcMPFr/OJUxS/rED+693xoU5pwEpQwy0hdN13D7T0+ET2l3jUsiLkk/GVTcX8vCm6YR74=
deploy:
  provider: releases
  api_key:
    secure: q9g1AI45HPefDxWcHcwxRGkAKLf+Ck5LmtKMs9PTNPEWKU506T+ErWXJfGaK+Z1tDwX6kp33zQGeMxz+P1Bjj25ZiRbsHS84/IuwRpNgeVgVtixetklruj3FjVj2Xvocy57LnC9wQlkg89m2cdhqaqf/rCbXbYIlV+/qVJXSXmw54STE+Ju00QD+Myn13BQdhOG9bLjZTjD7UVjxd8f+NoOOWxwayM/qsGZj3YWVFvWtiDT7ffKSs7s0/c5Q8hQiprMeJwcnFeZ28ZZQkFzGc+ceX/5+qW3UNFJZ94l9QsFj3cxXEz3RG91ylesz4PDYZ6BIp2M2GMfx13JaIZWuUbDO7hdlOKdjPcxfZxI7c5rm9Hvij8VTnjzDdftZOSIKZdJD2LLecWjB1+oxcAq8ToCEYvfDzutNUtEzAqFPs9Fk8P3pkosS5QzihnU2AV0pbrVONgKLSzaIuG4AVdF8T6SrQu7oez2jkPItdzBfur+YRK3LQYY1AnYJKH4j3CGLkr961zgkimWG2oueJMPZp1tOJGRmmviNWVhGxfqnG3rhY81RaV5X1YuPchHIR49TArxysuwjGczsQmkVadoFl53H7zqaIOYi51f0fDCNQa++Tg1ILlLRAux1dO2fIQyLae+uJGuC9elOR06y58QPWLkMtBGI/n6daqhNeAmZUwA=
  file:
  - "firmware.bin.gpg"
  on:
    tags: true
    repo: thu-skyworks/esp8266-door
